<div class="row">
    <div class="col-md-12" style="margin-top:10px;">
        <div class="panel panel-default">
            <div class="panel-heading uptransform clearfix" style="font-weight:bold;padding:8px 15px;font-size:17px;">
                <div class=" panel_product_heading " style="line-height:31px;font-size:17px;padding-left:0; display: inline-block;">
                    <?php //echo __('Invite Buyers');?>
                </div>            
                <div class="buttons-set buttons_scb" style="text-align:right; display: inline;">    
                    <button class="button btn btn-success uptransform product-button" title="<?= /* @noEscape */ __('Save') ?>" type="submit" onClick="jQuery('#form-validate').submit();" id="save_butn" style="float:right; margin-left: 10px;">
                        <span><span><?= /* @noEscape */ __('Submit') ?></span></span>
                    </button>
                </div>
            </div>

            <div class="panel-body">
                <div class="col-md-12">
                    <div class="fieldset">
                    <form class="form" action="<?= /* @noEscape */ $block->getUrl('csmembership/membership/pay') ?>" method="post" id="form-validate" autocomplete="off">
                    <input type="hidden" name="form_key" value="<?= /* @noEscape */ $block->getFormKey() ?>" />

                    <ul class="form-list">                        
                        <li class="wide">
                            <label class="label"><span><?= /* @noEscape */ __('Product Quantity'); ?></span></label>
                            <div class="input-box">
                                <input name="product_qty" title="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('Product Quantity')) ?>"  class="input-text validate-number validate-zero-or-greater required-entry" type="text" />
                            </div>
                        </li>
                        <li class="wide">
                            <label class="label"><span><?= /* @noEscape */ __('Auction Quantity'); ?></span></label>
                            <div class="input-box">
                                <input name="auction_qty" title="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('Auction Quantity')) ?>"  class="input-text validate-number validate-zero-or-greater required-entry" type="text" />
                            </div>
                        </li>
                        <li class="wide">
                            <label class="label"><span><?= /* @noEscape */ __('RFQ Quantity'); ?></span></label>
                            <div class="input-box">
                                <input name="rfq_qty" title="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('RFQ Quantity')) ?>"  class="input-text validate-number validate-zero-or-greater required-entry" type="text" />
                            </div>
                        </li>
                        <li class="wide">
                            <label class="label"><span><?= /* @noEscape */ __('Non Catalog RFQ Quantity'); ?></span></label>
                            <div class="input-box">
                                <input name="non_catalog_rfq_qty" title="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('Non Catalog RFQ Quantity')) ?>"  class="input-text validate-number validate-zero-or-greater required-entry" type="text" />
                            </div>
                        </li>                
                    </ul>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    require(['jquery'], function($){
        
        $(document).ready(function(){                

        });
    });
</script>
<script>
    require(["jquery","mage/mage"],function($){    
           $('#form-validate').mage('validation', {
               
           });
    });    
</script>