<?php
/** @var PrivateAuction $block */
/** @var PrivateAuctionForm $viewModel */

$auctions = $block->getAuctions();
$customers = $block->getCustomerCollection();
$viewModel = $block->getData('viewModel');

$auction_id = $block->getRequest()->getParam('id');
$details = $block->getPrivateAuctionDetails($auction_id);
$customer_ids = [];
if (!empty($details['customer_ids'])) {
    $customer_ids = explode(',', $details['customer_ids']);
}
$customer_emails = [];
if (!empty($details['customer_emails'])) {
    $customer_emails = $viewModel->unserialize($details['customer_emails']);
}

use Matrix\CsAuction\Block\PrivateAuction;
use OX\Auction\ViewModel\PrivateAuctionForm;

?>
<div class="row">
    <div class="col-md-12" style="margin-top:10px;">
        <div class="panel panel-default">
            <div class="panel-heading uptransform clearfix" style="font-weight:bold;padding:8px 15px;font-size:17px;">
                <div class=" panel_product_heading "
                     style="line-height:31px;font-size:17px;padding-left:0; display: inline-block;">
                    <?php //echo __('Invite Buyers');?>
                </div>
                <div class="buttons-set buttons_scb" style="text-align:right; display: inline;">
                    <button class="button btn btn-success uptransform product-button"
                            title="<?= $viewModel->escaper->escapeHtml(__('Post Auction')) ?>" type="submit"
                            id="save_butn"
                            style="float:right; margin-left: 10px;">
                        <span><span><?= $viewModel->escaper->escapeHtml(__('Post Auction')) ?></span></span>
                    </button>
                    <button class="button btn btn-success uptransform product-button" title="<?= $viewModel
                        ->escaper->escapeHtml(__('Exit')) ?>"
                            type="submit"
                            onClick="window.location.href='<?= $viewModel->escaper
                                ->escapeUrl($block->getUrl('csauction/auctionlist/index')) ?>';"
                            style="float:right;">
                        <span><span><?= $viewModel->escaper->escapeHtml(__('Exit')) ?></span></span>
                    </button>
                </div>
            </div>

            <div class="panel-body">
                <div class="col-md-12">
                    <div class="fieldset">
                        <form class="form"
                              action="<?= $viewModel->escaper
                                  ->escapeUrl($block->getUrl('csauction/auctionlist/saveprivateauction')) ?>"
                              method="post" id="form-validate" autocomplete="off">
                            <input type="hidden" name="form_key" value="<?= $viewModel->escaper
                                ->escapeUrl($block->getFormKey()) ?>"/>

                            <ul class="form-list">
                                <li class="wide">
                                    <label class="label"><span><?= $viewModel->escaper
                                                ->escapeHtml(__('Select Auction')); ?></span><span
                                            class="required">*</span></label>
                                    <div class="input-box">
                                        <select name="auction_id" class="select admin__control-select select2"
                                                data-validate="{required:true}">
                                            <option value=""><?= $viewModel->escaper
                                                    ->escapeHtml(__('Select Public/Private Auction')); ?></option>
                                            <?php foreach ($auctions as $auction): ?>
                                                <option
                                                    value="<?= $viewModel->escaper
                                                        ->escapeHtml($auction->getId()) ?>"
                                                    <?php if ($auction_id == $auction->getId()): ?>
                                                        <?= $viewModel->escaper
                                                            ->escapeHtml('selected'); ?>
                                                    <?php endif; ?>>
                                                    <?= $viewModel->escaper
                                                        ->escapeHtml($auction->getProductName() . ' (' . $auction
                                                                ->getStartingPrice() . ')') ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </li>
                                <li class="wide">
                                    <label class="label"><span><?= $viewModel->escaper
                                                ->escapeHtml(__('Invite Registered buyers')); ?></span>
                                        <span class="required">*</span>
                                    </label>
                                    <div class="input-box">
                                        <select name="customer_ids[]" multiple="multiple" size="10"
                                                class="select admin__control-multiselect select2"
                                                data-validate="{required:true}">
                                            <?php foreach ($customers as $customer): ?>
                                                <?php ?>
                                                <option
                                                    value="<?= $viewModel->escaper
                                                        ->escapeHtml($viewModel->getDtlCustOpt($customer)) ?>"
                                                    <?php if (isset($details['auction_id']) &&
                                                        in_array($customer->getId(), $customer_ids)): ?>
                                                        selected
                                                    <?php endif; ?>>
                                                    <?= $viewModel->escaper
                                                        ->escapeHtml($customer->getName() . ' - ' . $customer
                                                                ->getEmail()) ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </li>
                                <li class="wide">
                                    <label class="label"><span><?= $viewModel->escaper
                                                ->escapeHtml(__('Invite Non-Registered Buyers')); ?></span></label>
                                    <div class="input-box">
                                        <?php if (empty($customer_emails)): ?>
                                            <div class="control add-nonbuyer-form">
                                                <ul class="form-list nav">
                                                    <li class="wide">
                                                        <label
                                                            class="label">
                                                            <span><?= $viewModel->escaper
                                                                    ->escapeHtml(__('Company Name')); ?></span></label>
                                                        <div class="input-box">
                                                            <input name="company_name[]"
                                                                   title="<?= $viewModel->escaper
                                                                       ->escapeHtmlAttr(__('Company Name')) ?>"
                                                                   class="input-text" type="text"/>
                                                        </div>
                                                    </li>
                                                    <li class="wide">
                                                        <label
                                                            class="label"><span><?= $viewModel->escaper
                                                                    ->escapeHtml(__('First Name')); ?></span></label>
                                                        <div class="input-box">
                                                            <input name="first_name[]"
                                                                   title="<?= $viewModel->escaper
                                                                       ->escapeHtmlAttr(__('First Name')) ?>"
                                                                   class="input-text" type="text"/>
                                                        </div>
                                                    </li>
                                                    <li class="wide">
                                                        <label
                                                            class="label"><span><?= $viewModel->escaper
                                                                    ->escapeHtml(__('Last Name')); ?></span></label>
                                                        <div class="input-box">
                                                            <input name="last_name[]"
                                                                   title="<?= $viewModel->escaper
                                                                       ->escapeHtmlAttr(__('Last Name')) ?>"
                                                                   class="input-text" type="text"/>
                                                        </div>
                                                    </li>
                                                    <li class="wide">
                                                        <label class="label"><span><?= $viewModel->escaper
                                                                    ->escapeHtml(__('Email')); ?></span></label>
                                                        <div class="input-box">
                                                            <input name="customer_emails[]"
                                                                   title="<?= $viewModel->escaper
                                                                       ->escapeHtmlAttr(__('First Name')) ?>"
                                                                   class="input-text" type="text"/>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        <?php endif; ?>

                                        <?php if (!empty($customer_emails)): ?>
                                            <?php foreach ($customer_emails as $customer_email): ?>
                                                <div class="control add-nonbuyer-form">
                                                    <ul class="">
                                                        <li class="wide">
                                                            <label class="label">
                                                                <span><?= $viewModel->escaper
                                                                        ->escapeHtml(__('Company Name')); ?>
                                                                </span></label>
                                                            <div class="input-box">
                                                                <input name="company_name[]"
                                                                       title="<?= $viewModel->escaper
                                                                           ->escapeHtmlAttr(__('Company Name')) ?>"
                                                                       class="input-text" type="text"
                                                                       value="<?= $viewModel->escaper
                                                                           ->escapeHtml($customer_email['company_name']) ?>"/>
                                                            </div>
                                                        </li>
                                                        <li class="wide">
                                                            <label
                                                                class="label">
                                                                <span><?= $viewModel->escaper
                                                                        ->escapeHtml(__('First Name')); ?>
                                                                </span></label>
                                                            <div class="input-box">
                                                                <input name="first_name[]"
                                                                       title="<?= $viewModel->escaper
                                                                           ->escapeHtmlAttr(__('First Name')) ?>"
                                                                       class="input-text" type="text"
                                                                       value="<?= $viewModel->escaper
                                                                           ->escapeHtml($customer_email['first_name']) ?>"/>
                                                            </div>
                                                        </li>
                                                        <li class="wide">
                                                            <label
                                                                class="label">
                                                                <span><?= $viewModel->escaper
                                                                        ->escapeHtml(__('Last Name')); ?></span></label>
                                                            <div class="input-box">
                                                                <input name="last_name[]"
                                                                       title="<?= $viewModel->escaper
                                                                           ->escapeHtmlAttr(__('Last Name')) ?>"
                                                                       class="input-text" type="text"
                                                                       value="<?= $viewModel->escaper
                                                                           ->escapeHtml($customer_email['last_name']) ?>"/>
                                                            </div>
                                                        </li>
                                                        <li class="wide">
                                                            <label
                                                                class="label">
                                                                <span><?= $viewModel->escaper
                                                                        ->escapeHtml(__('Email')); ?></span></label>
                                                            <div class="input-box">
                                                                <input name="customer_emails[]"
                                                                       title="<?= $viewModel->escaper
                                                                           ->escapeHtmlAttr(__('First Name')) ?>"
                                                                       class="input-text" type="text"
                                                                       value="<?= $viewModel->escaper
                                                                           ->escapeHtml($customer_email['email']) ?>"/>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </div>
                                            <?php endforeach; ?>
                                        <?php endif; ?>

                                        <div class="field add_more_buyer"></div>

                                        <div class="field add_more">
                                            <a href="javascript:void(0);"
                                               class="button btn btn-success btn-right"><?= $viewModel->escaper
                                                    ->escapeHtml(__('Add More')) ?></a>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <div class="termlabel">
                                <span class="required">*</span> <input type="checkbox" name="terms"
                                                                       data-validate='{"required":true}'>
                                <label for="custom-terms" class="label label-agree ">
                                    <span><b><?= $viewModel->escaper->escapeHtml(__('I agree with the')) ?></b></span>
                                    <a href="javascript:void(0);"><?= $viewModel->escaper
                                            ->escapeHtml(__('Terms &amp; Conditions')) ?></a>
                                </label>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
   "*": {
       "OX_Auction/js/private-form": {}
   }
}



</script>

<style type="text/css">
    .mage-error {
        color: red;
    }

    .required {
        color: red;
    }

    .termlabel {
        text-align: right;
    }
</style>
