<?php
/**
 * Webkul Software
 *
 * @category  Webkul
 * @package   Webkul_Otp
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var $viewModel \Webkul\Otp\ViewModel\HelperViewModel */
$viewModel = $block->getViewModel();
$otpHelper = $viewModel->helper(\Webkul\Otp\Helper\Data::class);
$jsonHelper = $viewModel->helper(\Magento\Framework\Json\Helper\Data::class);

$isModuleEnable = $otpHelper->isModuleEnable();
$enableAtCheckout = $otpHelper->isEnableAtCheckout();
$isMobileOtpEnable = $otpHelper->getOtpEnabledConfigMessage();
$otpModalConfig = $otpHelper->getOtpModalConfig();
//@codingStandardsIgnoreStart
if ($isModuleEnable && $enableAtCheckout): ?>
    <div class="wk-otp-loading-mask wk-otp-display-none">
        <div class="wk-otp-loader"></div>
    </div>
    <div id="otp_modal" class="wk-otp-display-none">
        <div class="otp_popup">
            <p class="otp_expire_message">
            <?=__('Your OTP will expire in') . $escaper->escapeHtmlAttr($otpModalConfig
            ['otpTimeToExpireString']);/* @noEscape */?>
            </p>
            <div class="otp_response"></div>
            <div class="otp_action">
                <input name="otp" type="password" class="user_otp" id="user_otp" autocomplete="off">
                <button class="submit_otp">
                    <?=$escaper->escapeHtmlAttr($otpModalConfig['submitButtonText']);?>
                </button>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
    {
    "*":{
            "verifyMultishippingOtp": <?=/* @noEscape */$jsonHelper->jsonEncode($otpModalConfig);?>
        }
    }
    </script>
<?php endif; //@codingStandardsIgnoreEnd?>
