<?php
$currentQuote = $block->getQuote();
$chatDate = '';
?>
<form class="form noncatalogrfq"
      action="<?= /* @noEscape */  $block->getSendUrl();?>"
      id="noncatalogrfq"
      name="noncatalogrfq"
      method="post"
      data-hasrequired="<?= /* @noEscape */  $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
     data-mage-init='{"validation":{}}'>
<div>
                
                    <div class="purchaseorder-history-block" id="purchaseorder-history-block">
                        <?php if ($block->getChatHistory() && !empty($block->getChatHistory())) {?>
                        <div class="purchaseorder-comment-wrapper">
                            <ul class="note-list">
                                <?php foreach ($block->getChatHistory() as $_chathistory) {?>
                                    <?php if ($chatDate != date('Y-m-d', strtotime($_chathistory->getCreatedAt()))) {
                                        $chatDate = date('Y-m-d', strtotime($_chathistory->getCreatedAt()));
                                        ?>
                                        <li class="purchaseorder-middle-chat-column">
                                            <div class="chat-date"><?= /* @noEscape */  $chatDate; ?></div>
                                        </li>
                                    <?php } ?>
                                    <?php if ($_chathistory->getSentBy() == 'Customer') { ?>
                                        <li class="purchaseorder-right-chat-column">
                                            <strong> [<?= /* @noEscape */  __('Customer')?>]</strong>
                                            <?php if ($_chathistory->getMessage()) { ?>
                                                <div class="purchaseorder-right-chat-column-chat"><?= /* @noEscape */  $escaper->escapeHtml($_chathistory->getMessage(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?></div>
                                            <?php } ?>
                                        </li>
                                    <?php } elseif ($_chathistory->getSentBy() == 'Vendor') {?>
                                        <li class="purchaseorder-left-chat-column">
                                            <div class="purchaseorder-left-chat-column-chat">
                                                <strong><?= /* @noEscape */  __('Vendor')?></strong>
                                                <?php if ($_chathistory->getMessage()) { ?>
                                                    <div class="note-list-comment"><?= /* @noEscape */  $escaper->escapeHtml($_chathistory->getMessage(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </li>
                                    <?php } else {  ?>
                                        <li class="purchaseorder-left-chat-column" >
                                            <div class="purchaseorder-left-chat-column-chat">
                                                <strong><?= /* @noEscape */  __('Admin')?></strong>
                                                <?php if ($_chathistory->getMessage()) { ?>
                                                    <div class="note-list-comment"><?= /* @noEscape */  $escaper->escapeHtml($_chathistory->getMessage(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </li>
                                    <?php } ?>
                                <?php } ?>
                            </ul>
                        </div>
                        <?php } else {
                            echo "<div>No Chat</div>";
                        }?>
                        <div class="field text">
                            <label class="label" for="chat"><span><?= /* @noEscape */  /* @escapeNotVerified */ __('Message') ?></span></label>
                            <div class="control">
                                <textarea id="message" name="message" cols="60" rows="3"  data-validate="{required:true,'restrictUrl':true,'restrictEmail':true}"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit" name="send" value="send" title="<?= /* @noEscape */  /* @escapeNotVerified */ __('Send') ?>" class="action submit primary">
                                <span><?= /* @noEscape */  /* @escapeNotVerified */ __('Send') ?></span>
                            </button>
                        </div>
                    </div>
                
            </div>
</form>            

<script type="text/x-magento-init">
       {
           "*": {
               "noUrlValidation": {},
               "noEmailValidation":{}
           }
       }
</script>
