<?php
$nonCatalogRfq =  $block->getNonCatalogQuote();
$rfProduct =  $block->getRfqProducts();
$negotistionHistory =  $block->getNegotistionHistory();
//$arr_isaccpected = array(0=>'No',1=>'Yes');
$arr_isaccpected = [0=>'<i class="porto-icon-cancel"> No </i>',1=>'<i class="demo-icon porto-icon-ok"> Yes </i>'];
$_noncatRfqHelper = $block->helper('Matrix\NoncatalogueRfq\Helper\Data');
///echo $rfProduct->getData('rfq_product_id');
$uomOptions =  $_noncatRfqHelper->getUomOptions($rfProduct->getData('rfq_product_id'));
$uomlabel = '';
if ($rfProduct->getData('umo')>0) {
    $uomlabel = $uomOptions[$rfProduct->getData('umo')];
}
$pricingHelper = $block->helper('Magento\Framework\Pricing\Helper\Data');
?>

        <div class="data-table-wrapper">
            <h2><?= /* @noEscape */  __('Requested Price and Qty Information')?></h2>
            <div class="table-responsive mb-25">
            <table class="data-table table table-striped table-cus table-cus1">
                <thead>
                    <tr class="headings">
                        <th class="col-product"><span><?= /* @noEscape */  __("Product"); ?></span></th>
                        <th class="col-price"><span><?= /* @noEscape */  __("Unit Price"); ?></span></th>
                        <th class="col-ordered-qty"><span><?= /* @noEscape */  __("Qty"); ?></span></th>
                        <th class="col-total last"><span><?= /* @noEscape */  __("Row Total"); ?></span></th>
                    </tr>
                    <tr>
                        <td style="width:40%;"><?= /* @noEscape */  $rfProduct->getData('name');?></td>
                        <td><?= /* @noEscape */  $pricingHelper->currency($rfProduct->getData('target_price'), true, false);?></td>
                        <td><?= /* @noEscape */  $rfProduct->getData('qty') . ' ' . $uomlabel;?></td>
                        <td>
                            <?php
                            $rowTotal =$rfProduct->getData('target_price') * $rfProduct->getData('qty')
?>
                            <?= /* @noEscape */  $pricingHelper->currency($rowTotal, true, false);?>
                        </td>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            </div>
        </div>

        <div class="data-table-wrapper">
            <h2><?= /* @noEscape */  __('Negotiation Hisory')?></h2>
            <div class="table-responsive mb-25">
            <table class="data-table table table-striped table-cus table-cus1">
                <thead>
                    <tr class="headings">
                        <th class="col-price"><span><?= /* @noEscape */  __("Unit Price"); ?></span></th>
                        <th class="col-ordered-qty"><span><?= /* @noEscape */  __("Qty") . ' (' . $uomlabel . ')'; ?></span></th>
                        <th class="col-ordered-qty"><span><?= /* @noEscape */  __("Lead Time"); ?></span></th>
                        <th class="col-ordered-qty"><span><?= /* @noEscape */  __("Send By"); ?></span></th>
                        <th class="col-ordered-qty"><span><?= /* @noEscape */  __("Coment"); ?></span></th>
                        <th><span><?= /* @noEscape */  __("Accepected"); ?></span></th>
                        <th class="col-ordered-qty"><span><?= /* @noEscape */  __("Date"); ?></span></th>
                        <th class="col-ordered-qty"><span><?= /* @noEscape */  __("Action"); ?></span></th>
                    </tr>
                    <?php if ($negotistionHistory->getSize()) {
                        $count = 0;
                        $size = $negotistionHistory->getSize();
                        foreach ($negotistionHistory as $nhistory) {
                            $count++;?>
                      <tr>
                          <td>
                            <span style="padding:2px;text-decoration: line-through"><?= /* @noEscape */  $pricingHelper->currency($rfProduct->getData('target_price'), true, false);?></span> |
                            <span style="padding:2px;"><?= /* @noEscape */  $pricingHelper->currency($nhistory->getData('negotiotion_price'), true, false);?></span>
                          </td>
                          <td>
                              <span style="padding:2px;text-decoration: line-through"><?= /* @noEscape */  $rfProduct->getData('qty');?></span> |
                              <span style="padding:2px;"><?= /* @noEscape */  $nhistory->getData('negotiotion_qty');?></span>
                          </td>
                          <td>
                              <span style="padding:2px;text-decoration: line-through"> <?= /* @noEscape */  $nonCatalogRfq->getData('lead_time');?> </span> |
                              <span style="padding:2px;"><?= /* @noEscape */  $nhistory->getData('negotiotion_leadtime');?></span>
                          </td>
                          <td>
                              <?php if ($nhistory->getData('sent_by') == 'Customer') { ?>
                                      <span style="background:#a3be8c;color:#ffffff;padding:5px;" class="purchaseorder-right-chat-column-chat">You</span>
                                    <?php } elseif ($nhistory->getData('sent_by') == 'Vendor') {?>
                                        <?php
                                                $vendorModel = $block->getVendorbyId($nhistory->getVendorId());
                                        ?>
                                        <span style="background:#b48ead;color:#ffffff;padding:2px;" class="note-list-comment">
                                            <?= /* @noEscape */  $vendorModel->getData('public_name');?> [ <?= /* @noEscape */  __('Vendor')?> ]
                                        </span>
                               <?php }?>
                          </td>
                          <td width="10%"><span><a data-comment="<?= /* @noEscape */  $nhistory->getData('message');?>" title="<?= /* @noEscape */  __("Read more comment"); ?>" class="comment-readmore" href="javascript:void(0);"> Read</a></span></td>
                          <td><?= /* @noEscape */  $arr_isaccpected[$nhistory->getData('is_accpected')];?></td>
                          <td><?= /* @noEscape */  $block->getFormatedDate($nhistory->getData('created_at'));?></td>
                          <td>
                            <?php if (strtolower($nhistory->getData('sent_by'))=='vendor' && ($count==$size)) {?>
                                <?php if ($nhistory->getData('is_accpected')==1) {?>
                                    <span style='color:#aaaaaa'>Accepted</span>
                                <?php } else {?>
                                    <?php
                                    $nhistoryArray = $nhistory->toArray();
                                    $nhistoryArray['quoted_price'] = $pricingHelper->currency($nhistoryArray['quoted_price'], true, false);
                                    $nhistoryArray['negotiotion_price'] = $pricingHelper->currency($nhistoryArray['negotiotion_price'], true, false);
                                    $nhistoryArray['quoted_qty'] = $nhistoryArray['quoted_qty'] . ' ' . $uomlabel;
                                    $nhistoryArray['negotiotion_qty'] = $nhistoryArray['negotiotion_qty'] . ' ' . $uomlabel;
                                    $nhistoryArray['message'] = '';
                                    $nhistoryArray['custom']['target_price'] = $pricingHelper->currency($rfProduct->getData('target_price'));
                                    $nhistoryArray['custom']['negotiation_price'] = $pricingHelper->currency($nhistory->getData('negotiotion_price'));
                                    $nhistoryArray['custom']['target_qty'] = $rfProduct->getData('qty');
                                    $nhistoryArray['custom']['negotiated_qty'] = $nhistory->getData('negotiotion_qty');
                                    $nhistoryArray['custom']['lead_time'] = $nonCatalogRfq->getData('lead_time');
                                    $nhistoryArray['custom']['negotiation_leadtime'] = $nhistory->getData('negotiotion_leadtime');
                                    ?>
                                  <a class="reply-negotiation" title="Reply" href="javascript:void(0);" data-negotiotion='<?= /* @noEscape */  json_encode($nhistoryArray);?>'><i class="demo-icon porto-icon-reply"></i> </a> |
                                  <a class="accpect-negotiation"  title="Accept" data-negotiotion='<?= /* @noEscape */  json_encode($nhistoryArray);?>'> <i class="porto-icon-heart"></i></a>
                                 <?php }?>
                          <?php } else {?>
                              N/A | N/A
                          <?php }?>
                          </td>
                      </tr>
                    <?php }
                        } else {?>
                          <tr>
                              <td colspan="8"><span style="color:#ff2500;"><?= /* @noEscape */  __('No Negotiation Hisory found.')?></span></td>
                          </tr>
                    <?php }?>

                </thead>
                <tbody>
                </tbody>
            </table>
            </div>
        </div>
<div id="negotiateaccepet-popup" style="display:none;">
<form class="form noncatrfq"
      action="<?= /* @noEscape */  /* @escapeNotVerified */ $block->getNegotiateAccepetPostUrl(); ?>"
      name="form-negotiatecccept"
      id="form-negotiatecccept"
      method="POST"
      data-hasrequired="<?php /* @escapeNotVerified */ //echo __('* Required Fields')?>"
      data-mage-init='{"validation":{}}'>
      <input type="hidden" name="accepected_negotiate_id" id="accepected_negotiate_id" value="" />
</form>
</div>

<!--Start Add Negotiate Form-->
<div id="negotiate-popup" style="display:none;">
<form class="form noncatrfq"
      action="<?= /* @noEscape */  /* @escapeNotVerified */ $block->getNegotiatePostUrl(); ?>"
      name="form-negotiate"
      id="form-negotiate"
      method="POST"
      data-hasrequired="<?php /* @escapeNotVerified */ //echo __('* Required Fields')?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" style="padding:5px;">

    <table class="data-table admin__table-primary edit-order-table" id ="negotistion-table">
        <tbody class="even ced-rfq-po-row">
        <tr>
            <td><?= /* @noEscape */  /* @escapeNotVerified */ __('Proposed Qty') ?></td>
            <td><strong style="text-decoration: line-through" id="target_qty"></strong>|<strong id="negotiated_qty"></strong></td>
            <td><?= /* @noEscape */  /* @escapeNotVerified */ __('Negotiate Qty') ?></td>
            <td>
                <input type="text" name="negotiotion_qty" id="negotiotion_qty" data-validate="{required:true,'validate-number':true}"/>
            </td>
        </tr>
        <tr>
            <td><?= /* @noEscape */  /* @escapeNotVerified */ __('Proposed Unit Price') ?></td>
            <td><strong style="text-decoration: line-through" id="target_price"></strong>|<strong id="negotiated_price"></strong></td>
            <td><?= /* @noEscape */  /* @escapeNotVerified */ __('Negotiate Unit Price') ?></td>
            <td>
                <input type="text" name="negotiotion_price" id="negotiotion_price" data-validate="{required:true,'validate-number':true}}"/>
            </td>
        </tr>
        <tr>
            <td><?= /* @noEscape */  /* @escapeNotVerifescapeNotVerifiedied */ __('Proposed Delivery Lead Time') ?></td>
            <td><strong style="text-decoration: line-through" id="lead_time"></strong>|<strong id="negotiation_leadtime"></strong></td>
            <td><?= /* @noEscape */  /* @escapeNotVerified */ __('Your Lead Time') ?> </td>
            <td>
                <input type="text" name="lead_time" id="lead_time" data-validate="{required:true,'validate-number':true}"/>    <span><?= /* @noEscape */  __('Days');?></span>
            </td>
        </tr>

        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td><?= /* @noEscape */  /* @escapeNotVerified */ __('Comments') ?></td>
            <td>
                <textarea id="message" name="message" cols="60" rows="3" data-validate=""></textarea>
            </td>
        </tr>
        </tbody>
   </table>
   <div class="actions-toolbar">
       <input type="hidden" name="negotiate_id" id="negotiate_id" value="" />
        <div class="primary">
            <button type="submit" id="send" name="send" value="send"  title="<?= /* @noEscape */  /* @escapeNotVerified */ __('Send') ?>" class="action submit primary">
                <span><?= /* @noEscape */  /* @escapeNotVerified */ __('Send') ?></span>
            </button>
        </div>
     </div>
 </fieldset>
 </form>
</div>
<!--End Add Negotiate Form-->
<script type="text/javascript">
    require(["jquery", "Magento_Ui/js/modal/modal", "Magento_Ui/js/modal/confirm"],function($, modal, confirmation) {
         $(document).ready(function() {

              $(".comment-readmore").click(function(){
                 var comment =    $(this).data("comment");
                 alert(comment);
             });

             $(".accpect-negotiation").click(function(){
                 var negotiotion = $(this).data("negotiotion");
            
                $("#accepected_negotiate_id").val(negotiotion.id);
                 var content = "<table>";
                  content +="<tr><td colspan='2' style='background-color:#ffa94d;color:#ffffff;padding:5px;text-align:center;border-bottom:1px solid #ffffff;'><strong>Your Quote Rate & QTY</strong></td><td style='background-color:#FF7538;color:#ffffff;padding:5px;text-align:center;border-bottom:1px solid #ffffff;' colspan='2'><strong>Vendors Rate & QTY</strong></td></tr>";
                  content += "<tr><td style='background-color:#ffa94d;color:#ffffff;'>Quoted Qty</td><td style='background-color:#ffa94d;color:#ffffff;text-decoration: line-through'>"+negotiotion.quoted_qty+"</td><td style='background-color:#FF7538;color:#ffffff;'>QTY</td><td style='background-color:#FF7538;color:#ffffff;'><strong>"+negotiotion.negotiotion_qty+"</strong></td></tr>";
                  content += "<tr><td style='background-color:#ffa94d;color:#ffffff;'>Quoted Price</td><td style='background-color:#ffa94d;color:#ffffff;text-decoration: line-through'>"+negotiotion.quoted_price+"</td><td style='background-color:#FF7538;color:#ffffff;'>Price</td><td style='background-color:#FF7538;color:#ffffff;'><strong>"+negotiotion.negotiotion_price+"</strong></td></tr>";
                  content += "<tr><td style='background-color:#ffa94d;color:#ffffff;'> Quoted Lead Time</td><td style='background-color:#ffa94d;color:#ffffff;text-decoration: line-through'> "+negotiotion.quoted_leadtime+" Days</td><td style='background-color:#FF7538;color:#ffffff;'>Lead Time</td><td style='background-color:#FF7538;color:#ffffff;'> <strong>"+negotiotion.negotiotion_leadtime+" Days</strong></td></tr>";


                  content +="</table>";
                  confirmation({
                     title: $.mage.__('Accept Vendor Negotiated Rate'),
                     content: content,
                     actions: {
                         confirm: function(){
                            //AccepectNegotiation(negotiotion);

                            $("#form-negotiatecccept").submit();

                          },
                         cancel: function(){},
                         always: function(){}
                     }
                });
              });



         });

    });
</script>

<script type="text/x-magento-init">
        {
            "*": {
                "Matrix_NoncatalogueRfq/js/popup_data": {}
            }
        }
</script>

