<!--  /**
* CedCommerce
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
*
* @category    Ced
* @package     Ced_RegistrationForm
* @author      CedCommerce Core Team <connect@cedcommerce.com >
* @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
* @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/ -->

<?php

$_collection = $block->attrCollection();
$orderHelper = $this->helper('Ced\RegistrationForm\Helper\Order');
$coll = ($_collection->getData());
if (count($coll)>0) {
    ?><legend class="legend"><span><?= /* @noEscape */  __('Additional Fields') ?></span></legend><br><?php
}

$attributeCollection =[];
foreach ($coll as $k => $v) {

    $models = $orderHelper->getAttributeFactory()->load($v['attribute_code'], 'attribute_code')->getData();
    $v['sortorder'] = $models['sortorder'];
    $v['dependable_attribute'] = $models['dependable_attribute'];
    $attributeCollection[]  = $v;

}

function cmp($a, $b)
{

    if ($a['sortorder'] == $b['sortorder']) {
        return 0;
    }
    return ($a['sortorder'] < $b['sortorder']) ? -1 : 1;
}
usort($attributeCollection, "cmp");

$dependable = [];
foreach ($attributeCollection as $value) {
    if ($value['dependable_attribute'] !="") {
        $dependable[] = $value['dependable_attribute'];
    }
}

foreach ($attributeCollection as $Data) {
    $table = $model->create('Ced\RegistrationForm\Model\Attribute')->load($Data['attribute_id'], 'attribute_id')->getData();
    if ($table['is_dependent'] == 1) {
        continue;
    }
    if (in_array($Data['attribute_code'], $dependable)) {
        continue;
    }

    if ($Data['is_required'] == 1) { ?>
        <div class="field confirmation required">
            <label class="label" for="password-confirmation">
                <span><?= /* @noEscape */  $Data['frontend_label']?></span></label>
            <div class="control">
                <?php if ($Data['frontend_input'] == "textarea") {?>
                    <textarea rows="" cols="" class ="required-entry textarea" name="<?= /* @noEscape */  $Data['attribute_code'] ?>"></textarea>
                <?php }
                if ($Data['frontend_input'] == "date") {?>
                    <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="date_type required-entry">
                <?php }

                if ($Data['frontend_input'] == "text" && $table['is_time']==1) {?>
                    <input type="text" id="timepicker" class="timepicker"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="required-entry input-text">
                    <?php
                } elseif ($Data['frontend_input'] == "text") {?>
                    <input type="text" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="required-entry input-text">
                    <?php
                }
        if ($Data['frontend_input'] == "select") {?>
                    <select class="required-entry input-select" name="<?= /* @noEscape */  $Data['attribute_code'] ?>">
                        <?php $attribute = $model->create('\Magento\Eav\Model\Config')->getAttribute('customer', $Data['attribute_code']);
            $options = $attribute->getSource()->getAllOptions();?>
                        <?php foreach ($options as $instance) { ?>
                            <option value="<?= /* @noEscape */  $instance['value'] ?>"> <?= /* @noEscape */  $instance['label'] ?></option>
                        <?php } ?>
                    </select>
                <?php }
        if ($Data['frontend_input'] == "multiselect") {?>
                    <select width ="100" height="100"  class="required-entry input-select" name="<?= /* @noEscape */  $Data['attribute_code'] ?>[]"  multiple style=" height: 101px;">
                        <?php $attribute = $model->create('\Magento\Eav\Model\Config')->getAttribute('customer', $Data['attribute_code']);
            $options = $attribute->getSource()->getAllOptions();?>
                        <?php foreach ($options as $instance) { ?>
                            <?php if (!empty($instance['value'])) {?>
                                <option value="<?= /* @noEscape */  $instance['value'] ?>"> <?= /* @noEscape */  $instance['label'] ?></option>
                            <?php }?>
                        <?php } ?>
                    </select>
                <?php }
        if ($Data['frontend_input'] == "file") {?>
                    <input type="file" 
                           name="<?= /* @noEscape */  $Data['attribute_code']; ?>"
                           accept=".xls,.xlsx,.txt, vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" />
                    <strong>
                        <note>
                            <p><?= /* @noEscape */  __('Note: Allowed file types are txt,excel,csv.');?></p>
                        </note>
                    </strong>
                <?php }
        if ($Data['frontend_input'] == "image") {?>
                    <input type="file"  name="<?= /* @noEscape */  $Data['attribute_code']; ?>" accept="image/x-png,image/gif,image/jpeg" />
                    <strong>
                        <note>
                            <p><?= /* @noEscape */  __('Note: Allowed image types are png,jpg,jpeg,gif,bmp.');?></p>
                        </note>
                    </strong>
                <?php }
        ?>
            </div>
        </div>
    <?php } else {  ?>
        <div class="field ">
            <label class="label" for="password">
                <span><?= /* @noEscape */  $Data['frontend_label'] ?></span></label>
            <div class="control">
                <?php if ($Data['frontend_input'] == "textarea") {?>
                    <textarea class ="textarea" rows="" cols="" name="<?= /* @noEscape */  $Data['attribute_code'] ?>"></textarea>
                <?php }
                if ($Data['frontend_input'] == "date") {?>
                    <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="date_type" />
                <?php }
                if ($Data['frontend_input'] == "text" && $table['is_time']==1) {?>
                    <input type="text" class="timepicker" id="timepicker2" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="input-text"/>
                    <?php
                } elseif ($Data['frontend_input'] == "text") {?>
                    <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="input-text"/>
                    <?php
                }
        if ($Data['frontend_input'] == "select") {?>
                    <select name="<?= /* @noEscape */  $Data['attribute_code'] ?>" >
                        <?php $attribute = $model->create('\Magento\Eav\Model\Config')->getAttribute('customer', $Data['attribute_code']);
            $options = $attribute->getSource()->getAllOptions();?>
                        <?php foreach ($options as $instance) { ?>
                            <option value="<?= /* @noEscape */  $instance['value'] ?>"> <?= /* @noEscape */  $instance['label'] ?></option>
                        <?php } ?>
                    </select>
                <?php }
        if ($Data['frontend_input'] == "multiselect") {?>
                    <select name="<?= /* @noEscape */  $Data['attribute_code'] ?>[]"  multiple style=" height: 101px;">
                        <?php $attribute = $model->create('\Magento\Eav\Model\Config')->getAttribute('customer', $Data['attribute_code']);
            $options = $attribute->getSource()->getAllOptions();?>
                        <?php foreach ($options as $instance) { ?>
                            <?php if (!empty($instance['value'])) {?>
                            <option value="<?= /* @noEscape */  $instance['value'] ?>"> <?= /* @noEscape */  $instance['label'] ?></option>
                        <?php }?>
                    <?php } ?>
                    </select>
                <?php }
        if ($Data['frontend_input'] == "file") {?>
                    <input type="file" id = "<?= /* @noEscape */  $Data['attribute_code'] ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" />
                    <strong><note><?= /* @noEscape */  __('Note: Allowed file types are txt,excel,csv.');?></note></strong>
                <?php }
        if ($Data['frontend_input'] == "image") {?>
                    <input type="file" id = "<?= /* @noEscape */  $Data['attribute_code'] ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" onchange="ValidateFileUpload(this.id)" accept="image/x-png,image/gif,image/jpeg"/>
                    <strong><note><?= /* @noEscape */  __('Note: Allowed image types are png,jpg,jpeg,gif,bmp.');?></note></strong>
                <?php }
        ?>
            </div>
        </div>
    <?php }
    }
$flag1 = false;
$flag2 = false;
foreach ($attributeCollection as $Data) {
    $table = $model->create('Ced\RegistrationForm\Model\Attribute')->load($Data['attribute_id'], 'attribute_id')->getData();
    if (in_array($Data['attribute_code'], $dependable) && $table['is_dependent'] == 1) {
        $flag1 = true;
        ?>
        <div  class="field<?php if ($Data['is_required'] == 1) {
            echo " confirmation required";
        }?> ">
            <label class="label" for="password-confirmation" >
                <span><?= /* @noEscape */  $Data['frontend_label']?></span></label>
            <div class="control">
                <?php
                if ($Data['frontend_input'] == "select") { ?>
                    <select class="required-entry input-select <?= /* @noEscape */  'dependable_field_' . $Data['attribute_code']; ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  $Data['attribute_code'] ?>">


                        <?php $attribute = $model->create('\Magento\Eav\Model\Config')->getAttribute('customer', $Data['attribute_code']);
                    $options = $attribute->getSource()->getAllOptions();?>
                        <?php foreach ($options as $instance) { ?>
                            <option value="<?= /* @noEscape */  $instance['value'] ?>"> <?= /* @noEscape */  $instance['label'] ?></option>
                        <?php } ?>
                    </select>
                    <?php
                }
        ?>
            </div>
        </div>
        <?php
    }
    if ($table['is_dependent'] == 1 && $flag1 == true) {
        $models = $model->create('Ced\RegistrationForm\Model\Attribute')->load($Data['attribute_code'], 'attribute_code')->getData();
        ?>
        <div class="field" >
            <span class ="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>"><B><?= /* @noEscape */  $Data['frontend_label']?></B></span></label>
            <div class="control">
                <?php if ($Data['frontend_input'] == "textarea") {?>
                    <textarea class ="textarea" rows="" cols="" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" ></textarea>
                <?php }
                if ($Data['frontend_input'] == "date") {?>
                    <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="date_type" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" >
                <?php }
                if ($Data['frontend_input'] == "text" && $table['is_time']==1) {?>
                    <input type="text" class="timepicker" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="input-text">
                    <?php
                } elseif ($Data['frontend_input'] == "text") {?>
                    <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="input-text">
                    <?php
                }
        if ($Data['frontend_input'] == "select") {?>
                <select class="input-select" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" >
                    <select class="input-select <?= /* @noEscape */  'dependable_field_' . $Data['attribute_code']; ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  $Data['attribute_code'] ?>" onchange="myFunction(this.id)">
                        <?php $attribute = $model->create('\Magento\Eav\Model\Config')->getAttribute('customer', $Data['attribute_code']);
            $options = $attribute->getSource()->getAllOptions();?>
                        <?php foreach ($options as $instance) { ?>
                            <option value="<?= /* @noEscape */  $instance['value'] ?>"> <?= /* @noEscape */  $instance['label'] ?></option>
                        <?php } ?>
                    </select>
                    <?php }
        if ($Data['frontend_input'] == "multiselect") {?>
                        <select width ="100" height="100"  class="input-select" name="<?= /* @noEscape */  $Data['attribute_code'] ?>[]"  multiple style=" height: 101px;" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" >
                        <?php $attribute = $model->create('\Magento\Eav\Model\Config')->getAttribute('customer', $Data['attribute_code']);
            $options = $attribute->getSource()->getAllOptions();?>
                            <?php foreach ($options as $instance) { ?>
                                <?php if (!empty($instance['value'])) {?>
                                    <?php if (!empty($instance['value'])) {?>
                                        <option value="<?= /* @noEscape */  $instance['value'] ?>"> <?= /* @noEscape */  $instance['label'] ?></option>
                                    <?php }?>
                                <?php }?>
                            <?php } ?>
                        </select>
                    <?php }
        if ($Data['frontend_input'] == "file") {?>
                        <input type="file"  name="<?= /* @noEscape */  $Data['attribute_code']; ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>"  />
                        <strong><note><?= /* @noEscape */  __('Note: Allowed file types are txt,excel,csv.');?></note></strong>
                    <?php }
        if ($Data['frontend_input'] == "image") {?>
                        <input type="file"  name="<?= /* @noEscape */  $Data['attribute_code']; ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>"  accept= "image/x-png,image/gif,image/jpeg"/>
                        <strong><note><?= /* @noEscape */  __('Note: Allowed image types are png,jpg,jpeg,gif,bmp.');?></note></strong>
                    <?php }
        ?>
            </div>
        </div>
    <?php }

    if (in_array($Data['attribute_code'], $dependable) && $table['is_dependent'] != 1) {
        $flag2 = true;
        ?>
        <div class="field<?php if ($Data['is_required'] == 1) {
            echo " confirmation required";
        }?> ">
            <label class="label" for="password-confirmation">
                <span><?= /* @noEscape */  $Data['frontend_label']?></span></label>
            <div class="control">
                <?php
                if ($Data['frontend_input'] == "select") {?>
                    <select class="required-entry input-select <?= /* @noEscape */  'dependable_field_' . $Data['attribute_code']; ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  $Data['attribute_code'] ?>" onchange="myFunction(this.id)">
                        <?php $attribute = $model->create('\Magento\Eav\Model\Config')->getAttribute('customer', $Data['attribute_code']);
                    $options = $attribute->getSource()->getAllOptions();?>
                        <?php foreach ($options as $instance) { ?>
                            <option value="<?= /* @noEscape */  $instance['value'] ?>"> <?= /* @noEscape */  $instance['label'] ?></option>
                        <?php } ?>
                    </select>
                <?php }
                ?>
            </div>
        </div>
    <?php }
    if ($table['is_dependent'] == 1 && $flag2 == true) {
        $models = $model->create('Ced\RegistrationForm\Model\Attribute')->load($Data['attribute_code'], 'attribute_code')->getData();
        ?>
        <div>
            <span class ="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>"><B><?= /* @noEscape */  $Data['frontend_label']?></B></span></label>
            <div class="control">
                <?php if ($Data['frontend_input'] == "textarea") {?>
                    <textarea class =" textarea" rows="3" cols="40" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" ></textarea>
                <?php }
                if ($Data['frontend_input'] == "date") {?>
                    <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="date_type " id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" >
                <?php }
                if ($Data['frontend_input'] == "text") {?>
                    <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class=" input-text " id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" >
                <?php }
                if ($Data['frontend_input'] == "select") {?>
                    <select class="input-select <?= /* @noEscape */  'dependable_field_' . $Data['attribute_code']; ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  $Data['attribute_code'] ?>" onchange="myFunction(this.id)">
                        <?php $attribute = $model->create('\Magento\Eav\Model\Config')->getAttribute('customer', $Data['attribute_code']);
                    $options = $attribute->getSource()->getAllOptions();?>
                        <?php foreach ($options as $instance) { ?>
                            <option value="<?= /* @noEscape */  $instance['value'] ?>"> <?= /* @noEscape */  $instance['label'] ?></option>
                        <?php } ?>

                    </select>
                <?php }
                if ($Data['frontend_input'] == "multiselect") {?>
                    <select width ="100" height="100"  class=" input-select" name="<?= /* @noEscape */  $Data['attribute_code'] ?>[]"  multiple style=" height: 101px;" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" >
                        <?php $attribute = $model->create('\Magento\Eav\Model\Config')->getAttribute('customer', $Data['attribute_code']);
                    $options = $attribute->getSource()->getAllOptions();?>
                        <?php foreach ($options as $instance) { ?>
                            <?php if (!empty($instance['value'])) {?>
                            <option value="<?= /* @noEscape */  $instance['value'] ?>"> <?= /* @noEscape */  $instance['label'] ?></option>
                        <?php }?>
                        <?php } ?>
                    </select>
                <?php }
                if ($Data['frontend_input'] == "file") {?>
                    <input type="file"  name="<?= /* @noEscape */  $Data['attribute_code']; ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>"  />
                    <strong><note><?= /* @noEscape */  __('Note: Allowed file types are txt,excel,csv.');?></note></strong>
                <?php }
                if ($Data['frontend_input'] == "image") {?>
                    <input type="file"  name="<?= /* @noEscape */  $Data['attribute_code']; ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" accept="image/x-png,image/gif,image/jpeg" />
                    <strong><note><?= /* @noEscape */  __('Note: Allowed image types are png,jpg,jpeg,gif,bmp.');?></note></strong>
                <?php }
                ?>
            </div>
        </div>
    <?php }
    }

//    }?>
</fieldset>
<script>
    require([
        "jquery",
        "mage/calendar",
    ], function ($){
        $.each($('.date_type'),function(i,v){
            $(this).calendar({showsTime: false,dateFormat: "M/d/yy"});
        });
    });
    require([
        "jquery",
        "jquery/jquery-ui-timepicker-addon",
    ], function ($){
        $.each($('.timepicker'),function(i,v){
            $(this).timepicker({showsTime: true});
        });
    });


    function myFunction(x) {
        require(["jquery"], function ($) {
            var depend = 'dependable'+x;

            var field  = document.getElementById(x).value;

            if(field !=1)
            {
                $("#"+depend).css('display','none');
                $("."+depend).css('display','none');
            }
            else{
                $("#"+depend).css('display','');
                $("."+depend).css('display','');
            }
        }); }

    function ValidateFileUpload(id) {
        require(["jquery"], function ($) {
            var fuData = document.getElementById(id);
            var FileUploadPath = fuData.value;

            //To check if user upload any file
            if (FileUploadPath == '') {
                // alert("Please upload an image");

            } else {
                var Extension = FileUploadPath.substring(
                    FileUploadPath.lastIndexOf('.') + 1).toLowerCase();



                if (Extension == "gif" || Extension == "png" || Extension == "bmp"
                    || Extension == "jpeg" || Extension == "jpg") {

                }
                else {
                    alert("Photo only allows file types of GIF, PNG, JPG, JPEG and BMP. ");

                }
            }
        });
    }


</script>
