<!--  /**
* CedCommerce
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
*
* @category    Ced
* @package     Ced_RegistrationForm
* @author      CedCommerce Core Team <connect@cedcommerce.com >
* @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
* @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/ -->
<?php $orderHelper = $this->helper('Ced\RegistrationForm\Helper\Order'); ?>
<form class="form form-edit-account" action="<?= /* @noEscape */  $block->getUrl("regform/additional/save/") ?>" method="post" id="form-validate" enctype="multipart/form-data" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= /* @noEscape */   __('* Required Fields') ?>">
        <legend class="legend"><span><?= /* @noEscape */  __('Additional Fields') ?></span></legend><br>
        <?php
        $_collection = $block->attrCollection();
$coll = ($_collection->getData());
$attributeCollection =[];
foreach ($coll as $k => $v) {
    $models = $orderHelper->getAttributeFactory()->load($v['attribute_code'], 'attribute_code')->getData();
    $v['sortorder'] = $models['sortorder'];
    $v['dependable_attribute'] = $models['dependable_attribute'];
    $attributeCollection[]  = $v;
}

function cmp($a, $b)
{
    if ($a['sortorder'] == $b['sortorder']) {
        return 0;
    }
    return ($a['sortorder'] < $b['sortorder']) ? -1 : 1;
}
usort($attributeCollection, "cmp");
$dependable = [];
foreach ($attributeCollection as $value) {
    if ($value['dependable_attribute'] !="") {
        $dependable[] = $value['dependable_attribute'];
    }
}
foreach ($attributeCollection as $Data) {
    $_customerData = $block->getCustomer()->getData();
    $usedInForms = $block->getForms($Data['attribute_id']);
    $isShowOnEditPage = in_array('customer_account_edit', $usedInForms);?>
            <?php $inputValue = '';
    foreach ($_customerData as $key => $value) {
        if ($Data['attribute_code'] == $key) {
            if ($Data['frontend_input'] == 'date') {
                $inputValue = $value;
            } elseif ($Data['frontend_input'] == 'boolean') {
                $inputValue = 'checked';
            } elseif ($Data['frontend_input'] == 'select') {
                $inputValue = $value;
            } elseif ($Data['frontend_input'] == 'multiselect') {
                $inputValue = $value;
            } elseif ($Data['frontend_input'] == 'image') {
                $inputValue = "<img class='images' width='75' height='75' alt='image' src='" . $block->getUrl() . 'pub/media/' . $value . "'/>";
            } elseif ($Data['frontend_input'] == 'file') {
                $inputValue = "<a class='images' alt='file' href='" . $block->getUrl() . 'pub/media/' . $value . "'>" . $value . "</a>";
            } else {
                $inputValue = $value;
            }
        }
    }
    $table = $orderHelper->getAttributeFactory()->load($Data['attribute_id'], 'attribute_id')->getData();
    if ($table['is_dependent'] == 1) {
        continue;
    }
    if (in_array($Data['attribute_code'], $dependable)) {
        continue;
    }
    $Data['is_required'] = 1;
    if ($Data['is_required'] == 1) { ?>
                <div class="field confirmation required">
                    <label class="label" for="password-confirmation">
                        <span><?= /* @noEscape */  $Data['frontend_label']?></span></label>
                    <div class="control">
                        <?php if ($Data['frontend_input'] == "textarea") { ?>
                            <textarea rows="" cols="" class ="required-entry textarea" name="<?= /* @noEscape */  $Data['attribute_code'] ?>"><?= /* @noEscape */  $inputValue; ?></textarea>

                        <?php     }
        if ($Data['frontend_input'] == "date") {?>
                            <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="date_type required-entry" value="<?= /* @noEscape */  $inputValue; ?>">
                        <?php }

        if ($Data['frontend_input'] == "text" && $table['is_time']==1) {?>
                            <input type="text" class="timepicker"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="required-entry input-text" value="<?= /* @noEscape */  $inputValue; ?>">
                            <?php
        } elseif ($Data['frontend_input'] == "text") {?>
                            <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="required-entry input-text" value="<?= /* @noEscape */  $inputValue; ?>">
                            <?php

        }
        if ($Data['frontend_input'] == "select") {  ?>
                            <select class="required-entry input-select" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" >
                                <?php $attribute =  $orderHelper->getAttribute($Data['attribute_code']);
            $options = $attribute->getSource()->getAllOptions();?>
                                <?php foreach ($options as $instance) { ?>
                                    <option value="<?= /* @noEscape */  $instance['value'] ?>" <?= /* @noEscape */  $inputValue==$instance['value'] ? 'selected' : ''; ?>> <?= /* @noEscape */  $instance['label'] ?></option>
                                <?php } ?>

                            </select>
                        <?php }
        if ($Data['frontend_input'] == "multiselect") {?>
                            <select width ="100" height="100"  class="required-entry input-select" name="<?= /* @noEscape */  $Data['attribute_code'] ?>[]"  multiple style=" height: 101px;">
                                <?php $attribute =  $orderHelper->getAttribute($Data['attribute_code']);
            $options = $attribute->getSource()->getAllOptions();?>
                                <?php foreach ($options as $instance) { ?>
                                    <option value="<?= /* @noEscape */  $instance['value'] ?>" <?= /* @noEscape */  $inputValue==$instance['value'] ? 'selected' : ''; ?>> <?= /* @noEscape */  $instance['label'] ?></option>
                                <?php } ?>
                            </select>
                        <?php }
        if ($Data['frontend_input'] == "file") {?>
                            <input type="file"  name="<?= /* @noEscape */  $Data['attribute_code']; ?>" />
                            <span class="note"><span><?= /* @noEscape */  $Data['note'] ?></span></span><br>
                            <span><?= /* @noEscape */  $inputValue; ?></span>
                        <?php }
        if ($Data['frontend_input'] == "image") {?>
                            <input type="file"  name="<?= /* @noEscape */  $Data['attribute_code']; ?>" />
                            <span class="note"><span><?= /* @noEscape */  $Data['note'] ?></span></span><br>
                            <div id="images_container">
                                <?= /* @noEscape */  $inputValue; ?>
                            </div>
                        <?php }
        ?>
                    </div>
                </div>
            <?php } else {?>
                <div class="field ">
                    <label class="label" for="password">
                        <span><?= /* @noEscape */  $Data['frontend_label'] ?></span></label>
                    <div class="control">
                        <?php if ($Data['frontend_input'] == "textarea") {?>
                            <textarea class ="textarea" rows="" cols="" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" value="<?= /* @noEscape */  $inputValue; ?>"><?= /* @noEscape */  $inputValue; ?></textarea>
                        <?php     }
                if ($Data['frontend_input'] == "date") {?>
                            <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="date_type" value="<?= /* @noEscape */  $inputValue; ?>">
                        <?php }
                if ($Data['frontend_input'] == "text" && $table['is_time']==1) {?>
                            <input type="text" class="timepicker"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="input-text" value="<?= /* @noEscape */  $inputValue; ?>">
                            <?php
                } elseif ($Data['frontend_input'] == "text") {?>
                            <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="input-text" value="<?= /* @noEscape */  $inputValue; ?>">
                            <?php
                }
                if ($Data['frontend_input'] == "select") {?>
                            <select name="<?= /* @noEscape */  $Data['attribute_code'] ?>"  >
                                <?php $attribute =  $orderHelper->getAttribute($Data['attribute_code']);
                    $options = $attribute->getSource()->getAllOptions();?>
                                <?php foreach ($options as $instance) { ?>
                                    <option value="<?= /* @noEscape */  $instance['value'] ?>" <?= /* @noEscape */  $inputValue==$instance['value'] ? 'selected' : ''; ?>> <?= /* @noEscape */  $instance['label'] ?></option>
                                <?php } ?>
                            </select>
                        <?php }
                if ($Data['frontend_input'] == "multiselect") {?>
                            <select name="<?= /* @noEscape */  $Data['attribute_code'] ?>[]"  multiple style=" height: 101px;" value="<?= /* @noEscape */  $inputValue; ?>">
                                <?php $attribute =  $orderHelper->getAttribute($Data['attribute_code']);
                    $options = $attribute->getSource()->getAllOptions();?>
                                <?php foreach ($options as $instance) { ?>
                                    <option value="<?= /* @noEscape */  $instance['value'] ?>" <?= /* @noEscape */  $inputValue==$instance['value'] ? 'selected' : ''; ?>> <?= /* @noEscape */  $instance['label'] ?></option>
                                <?php } ?>
                            </select>
                        <?php }
                if ($Data['frontend_input'] == "file") {?>
                            <input type="file" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" />
                            <span class="note"><span><?= /* @noEscape */  $Data['note'] ?></span></span><br>
                            <span><?= /* @noEscape */  $inputValue; ?></span>
                        <?php }
                if ($Data['frontend_input'] == "image") {?>
                            <input type="file" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" />
                            <span class="note"><span><?= /* @noEscape */  $Data['note'] ?></span></span><br>
                            <div id="images_container"></div>
                            <?= /* @noEscape */  $inputValue; ?>
                        <?php }
                ?>
                    </div></div>
            <?php     }
}
$flag1 = false;
$flag2 = false;
foreach ($attributeCollection as $Data) {
    $table = $orderHelper->getAttributeFactory()->load($Data['attribute_id'], 'attribute_id')->getData();
    if (in_array($Data['attribute_code'], $dependable) && $table['is_dependent'] == 1) {
        $flag1 = true;
        $_customerData = $block->getCustomer()->toArray();
        $usedInForms = $block->getForms($Data['attribute_id']);
        $isShowOnEditPage = in_array('customer_account_edit', $usedInForms);?>
                <?php $inputValue = '';

        foreach ($_customerData as $key => $value) {
            if ($Data['attribute_code'] == $key) {
                if ($Data['frontend_input'] == 'date') {
                    //$inputValue = $this->formatDate($value, \IntlDateFormatter::SHORT, false);
                    $inputValue = $value;
                } elseif ($Data['frontend_input'] == 'boolean') {
                    $inputValue = 'checked';
                } elseif ($Data['frontend_input'] == 'select') {
                    $inputValue = $value;
                } elseif ($Data['frontend_input'] == 'multiselect') {
                    $inputValue = $value;
                } elseif ($Data['frontend_input'] == 'image') {
                    $inputValue = "<img class='images' width='75' height='75' alt='image' src='" . $block->getUrl() . 'pub/media/' . $value . "'/>";
                } elseif ($Data['frontend_input'] == 'file') {
                    $inputValue = "<a class='images' alt='file' href='" . $block->getUrl() . 'pub/media/' . $value . "'>" . $value . "</a>";
                } else {
                    $inputValue = $value;
                }
            }
        }
        ?>
                <div  class="field<?php if ($Data['is_required'] == 1) {
                    echo " confirmation required";
                }?> ">
                    <label class="label" for="password-confirmation" >
                        <span><?= /* @noEscape */  $Data['frontend_label']?></span></label>
                    <div class="control">
                        <?php
                        if ($Data['frontend_input'] == "select") {?>
                            <select class="input-select <?= /* @noEscape */  'dependable_field_' . $Data['attribute_code']; ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  $Data['attribute_code'] ?>" value="<?= /* @noEscape */  $inputValue; ?>">
                                <?php $attribute =  $orderHelper->getAttribute($Data['attribute_code']);
                            $options = $attribute->getSource()->getAllOptions();?>
                                <?php foreach ($options as $instance) { ?>
                                    <option value="<?= /* @noEscape */  $instance['value'] ?>" <?= /* @noEscape */  $inputValue==$instance['value'] ? 'selected' : ''; ?>> <?= /* @noEscape */  $instance['label'] ?></option>
                                <?php } ?>
                            </select>
                            <?php
                        }
        ?>
                    </div>
                </div>
                <?php
    }
    if ($table['is_dependent'] == 1 && $flag1 == true) {
        $_customerData = $block->getCustomer()->toArray();
        $usedInForms = $block->getForms($Data['attribute_id']);
        $isShowOnEditPage = in_array('customer_account_edit', $usedInForms);?>
                <?php $inputValue = '';
        foreach ($_customerData as $key => $value) {
            if ($Data['attribute_code'] == $key) {
                if ($Data['frontend_input'] == 'date') {
                    //$inputValue = $this->formatDate($value, \IntlDateFormatter::SHORT, false);
                    $inputValue = $value;
                } elseif ($Data['frontend_input'] == 'boolean') {
                    $inputValue = 'checked';
                } elseif ($Data['frontend_input'] == 'select') {
                    $inputValue = $value;
                } elseif ($Data['frontend_input'] == 'multiselect') {
                    $inputValue = $value;
                } elseif ($Data['frontend_input'] == 'image') {
                    $inputValue = "<img class='images' width='75' height='75' alt='image' src='" . $block->getUrl() . 'pub/media/' . $value . "'/>";
                } elseif ($Data['frontend_input'] == 'file') {
                    $inputValue = "<a class='images' alt='file' href='" . $block->getUrl() . 'pub/media/' . $value . "'>" . $value . "</a>";
                } else {
                    $inputValue = $value;
                }
            }
        }
        $models = $orderHelper->getAttributeFactory()->load($Data['attribute_code'], 'attribute_code')->getData();
        ?>
                <div  class="field<?php if ($Data['is_required'] == 1) {
                    /* @noEscape */ echo __("confirmation required");
                }?> ">
                    <span class ="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>"><B><?= /* @noEscape */  $Data['frontend_label']?></B></span></label>
                    <div class="control">
                        <?php if ($Data['frontend_input'] == "textarea") {?>
                            <textarea class ="textarea" rows="" cols="" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" value="<?= /* @noEscape */  $inputValue; ?>"><?= /* @noEscape */  $inputValue; ?></textarea>
                        <?php     }
        if ($Data['frontend_input'] == "date") {?>
                            <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="date_type" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" value="<?= /* @noEscape */  $inputValue; ?>" >
                        <?php }
        if ($Data['frontend_input'] == "text" && $table['is_time']==1) {?>
                            <input type="text" class="timepicker"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" class="input-text" value="<?= /* @noEscape */  $inputValue; ?>">
                            <?php
        } elseif ($Data['frontend_input'] == "text") {?>
                            <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="input-text" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" value="<?= /* @noEscape */  $inputValue; ?>">
                            <?php
        }
        if ($Data['frontend_input'] == "select") {?>
                        <select class="input-select" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" value="<?= /* @noEscape */  $inputValue; ?>" >
                            <select class="input-select <?= /* @noEscape */  'dependable_field_' . $Data['attribute_code']; ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  $Data['attribute_code'] ?>" onchange="myFunction(this.id)">
                                <?php $attribute =  $orderHelper->getAttribute($Data['attribute_code']);
            $options = $attribute->getSource()->getAllOptions();?>
                                <?php foreach ($options as $instance) { ?>
                                    <option value="<?= /* @noEscape */  $instance['value'] ?>"> <?= /* @noEscape */  $instance['label'] ?></option>
                                <?php } ?>
                            </select>
                            <?php }
        if ($Data['frontend_input'] == "multiselect") {?>
                                <select width ="100" height="100"  class=" input-select" name="<?= /* @noEscape */  $Data['attribute_code'] ?>[]"  multiple style=" height: 101px;" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" value="<?= /* @noEscape */  $inputValue; ?>" >
                                <?php $attribute = $orderHelper->getAttribute($Data['attribute_code']);
            $options = $attribute->getSource()->getAllOptions();?>
                                    <?php foreach ($options as $instance) { ?>
                                        <option value="<?= /* @noEscape */  $instance['value'] ?>" <?= /* @noEscape */  $inputValue==$instance['value'] ? 'selected' : ''; ?>> <?= /* @noEscape */  $instance['label'] ?></option>
                                    <?php } ?>
                                </select>
                            <?php }
        if ($Data['frontend_input'] == "file") {?>
                                <input type="file"  name="<?= /* @noEscape */  $Data['attribute_code']; ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>"  />
                                <span class="note"><span><?= /* @noEscape */  $Data['note'] ?></span></span><br>
                                <span><?= /* @noEscape */  $inputValue; ?></span>
                            <?php }
        if ($Data['frontend_input'] == "image") {?>
                                <input type="file"  name="<?= /* @noEscape */  $Data['attribute_code']; ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>"  />
                                <span class="note"><span><?= /* @noEscape */  $Data['note'] ?></span></span><br>
                                <div id="images_container">
                                <?= /* @noEscape */  $inputValue; ?> </div>
                            <?php }
        ?>
                    </div>
                </div>
            <?php }

    if (in_array($Data['attribute_code'], $dependable) && $table['is_dependent'] != 1) {
        $flag2 = true;
        $_customerData = $block->getCustomer()->toArray();
        $usedInForms = $block->getForms($Data['attribute_id']);
        $isShowOnEditPage = in_array('customer_account_edit', $usedInForms);?>
                <?php $inputValue = '';
        foreach ($_customerData as $key => $value) {
            if ($Data['attribute_code'] == $key) {
                if ($Data['frontend_input'] == 'date') {
                    //$inputValue = $this->formatDate($value, \IntlDateFormatter::SHORT, false);
                    $inputValue = $value;
                } elseif ($Data['frontend_input'] == 'boolean') {
                    $inputValue = 'checked';
                } elseif ($Data['frontend_input'] == 'select') {
                    $inputValue = $value;
                } elseif ($Data['frontend_input'] == 'multiselect') {
                    $inputValue = $value;
                } elseif ($Data['frontend_input'] == 'image') {
                    $inputValue = "<img class='images' width='75' height='75' alt='image' src='" . $block->getUrl() . 'pub/media/' . $value . "'/>";
                } elseif ($Data['frontend_input'] == 'file') {
                    $inputValue = "<a class='images' alt='file' href='" . $block->getUrl() . 'pub/media/' . $value . "'>" . $value . "</a>";
                } else {
                    $inputValue = $value;
                }
            }
        }

        ?>
                <div  class="field<?php if ($Data['is_required'] == 1) {
                    echo " confirmation required";
                }?> ">
                    <label class="label" for="password-confirmation">
                        <span><?= /* @noEscape */  $Data['frontend_label']?></span></label>
                    <div class="control">
                        <?php
                        if ($Data['frontend_input'] == "select") {?>
                            <select class="input-select <?= /* @noEscape */  'dependable_field_' . $Data['attribute_code']; ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  $Data['attribute_code'] ?>" onchange="myFunction(this.id)">
                                <?php $attribute = $orderHelper->getAttribute($Data['attribute_code']);
                            $options = $attribute->getSource()->getAllOptions();?>
                                <?php foreach ($options as $instance) { ?>
                                    <option value="<?= /* @noEscape */  $instance['value'] ?>" <?= /* @noEscape */  $inputValue==$instance['value'] ? 'selected' : ''; ?>> <?= /* @noEscape */  $instance['label'] ?></option>
                                <?php } ?>
                            </select>
                        <?php }
                        ?>
                    </div>
                </div>
            <?php     }
    if ($table['is_dependent'] == 1 && $flag2 == true) {
        $_customerData = $block->getCustomer()->toArray();
        $usedInForms = $block->getForms($Data['attribute_id']);
        $isShowOnEditPage = in_array('customer_account_edit', $usedInForms);?>
                <?php $inputValue = '';
        foreach ($_customerData as $key => $value) {
            if ($Data['attribute_code'] == $key) {
                if ($Data['frontend_input'] == 'date') {
                    //$inputValue = $this->formatDate($value, \IntlDateFormatter::SHORT, false);
                    $inputValue = $value;
                } elseif ($Data['frontend_input'] == 'boolean') {
                    $inputValue = 'checked';
                } elseif ($Data['frontend_input'] == 'select') {
                    $inputValue = $value;
                } elseif ($Data['frontend_input'] == 'multiselect') {
                    $inputValue = $value;
                } elseif ($Data['frontend_input'] == 'image') {
                    $inputValue = "<img class='images' width='75' height='75' alt='image' src='" . $block->getUrl() . 'pub/media/' . $value . "'/>";
                } elseif ($Data['frontend_input'] == 'file') {
                    $inputValue = "<a class='images' alt='file' href='" . $block->getUrl() . 'pub/media/' . $value . "'>" . $value . "</a>";
                } else {

                    $inputValue = $value;
                }
            }
        }
        $models = $orderHelper->getAttributeFactory()->load($Data['attribute_code'], 'attribute_code')->getData();
        ?>
                <div  class="field<?php if ($Data['is_required'] == 1) {
                    /* @noEscape */ echo __("confirmation required");
                }?> ">
                    <span class ="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>"><B><?= /* @noEscape */  $Data['frontend_label']?></B></span></label>
                    <div class="control">
                        <?php if ($Data['frontend_input'] == "textarea") {?>
                            <textarea class ="textarea" rows="" cols="" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" value="<?= /* @noEscape */  $inputValue; ?>"><?= /* @noEscape */  $inputValue; ?></textarea>
                        <?php     }
        if ($Data['frontend_input'] == "date") {?>
                            <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="date_type" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" value="<?= /* @noEscape */  $inputValue; ?>">
                        <?php }
        if ($Data['frontend_input'] == "text" && $table['is_time']==1) {?>
                            <input type="text" class="timepicker"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" class="input-text" value="<?= /* @noEscape */  $inputValue; ?>">
                            <?php
        } elseif ($Data['frontend_input'] == "text") {?>
                            <input type="text"  name="<?= /* @noEscape */  $Data['attribute_code'] ?>" class="input-text" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" value="<?= /* @noEscape */  $inputValue; ?>">
                            <?php
        }
        if ($Data['frontend_input'] == "select") {?>
                            <select class="input-select <?= /* @noEscape */  'dependable_field_' . $Data['attribute_code']; ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" name="<?= /* @noEscape */  $Data['attribute_code'] ?>" id="<?= /* @noEscape */  $Data['attribute_code'] ?>" onchange="myFunction(this.id)">
                                <?php $attribute =  $orderHelper->getAttribute($Data['attribute_code']);
            $options = $attribute->getSource()->getAllOptions();?>
                                <?php foreach ($options as $instance) { ?>
                                    <option value="<?= /* @noEscape */  $instance['value'] ?>" <?= /* @noEscape */  $inputValue==$instance['value'] ? 'selected' : ''; ?>> <?= /* @noEscape */  $instance['label'] ?></option>
                                <?php } ?>
                            </select>
                        <?php }
        if ($Data['frontend_input'] == "multiselect") {?>
                            <select width ="100" height="100"  class="input-select" name="<?= /* @noEscape */  $Data['attribute_code'] ?>[]"  multiple style=" height: 101px;" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" >
                                <?php $attribute =  $orderHelper->getAttribute($Data['attribute_code']);
            $options = $attribute->getSource()->getAllOptions();?>
                                <?php foreach ($options as $instance) { ?>
                                    <option value="<?= /* @noEscape */  $instance['value'] ?>" <?= /* @noEscape */  $inputValue==$instance['value'] ? 'selected' : ''; ?>> <?= /* @noEscape */  $instance['label'] ?></option>
                                <?php } ?>
                            </select>
                        <?php }
        if ($Data['frontend_input'] == "file") {?>
                            <input type="file"  name="<?= /* @noEscape */  $Data['attribute_code']; ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" value="<?= /* @noEscape */  $inputValue; ?>"  />
                            <span class="note"><span><?= /* @noEscape */  $Data['note'] ?></span></span><br>
                            <span><?= /* @noEscape */  $inputValue; ?></span>
                        <?php }
        if ($Data['frontend_input'] == "image") {?>
                            <input type="file"  name="<?= /* @noEscape */  $Data['attribute_code']; ?>" id="<?= /* @noEscape */  'dependable' . $models['dependable_attribute'] ?>" value="<?= /* @noEscape */  $inputValue; ?>" />
                            <span class="note"><span><?= /* @noEscape */  $Data['note'] ?></span></span><br>
                            <div id="images_container">
                                <?= /* @noEscape */  $inputValue; ?>
                            </div>
                        <?php }
        ?>
                    </div>
                </div>
            <?php }
    }

$att_code = [];
$datas = $orderHelper->getAttributeCollection()->getCollection()->AddFieldToFilter('values', 'yes,no')->getData();
foreach ($datas as $data) {
    $att_code[] = $data['attribute_code'];
}
//    }?>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" title="Save"><span><?= /* @noEscape */  __("Save")?></span></button>
            </div>
        </div>

    </fieldset>
    <script>
        require([
            "jquery",
            "mage/calendar",
        ], function ($){
            $.each($('.date_type'),function(i,v){
                $(this).calendar({showsTime: false,dateFormat: "yy/m/d"});
            });
        });

        require(["jquery"], function ($) {
            $( document ).ready(function() {
                var myJavascriptData = <?= /* @noEscape */  json_encode($att_code) ?>;
                var arrayLength = myJavascriptData.length;
                for (var i = 0; i < arrayLength; i++)
                {
                    var depend = 'dependable'+myJavascriptData[i];
                    var field  = document.getElementById(myJavascriptData[i]).value;
                    if(field !=1)
                    {
                        $("#"+depend).css('display','none');
                        $("."+depend).css('display','none');
                    }
                    else
                    {
                        $("#"+depend).css('display','');
                        $("."+depend).css('display','');
                    }
                }
            });
        });

        require([
            "jquery",
            "jquery/jquery-ui-timepicker-addon",
        ], function ($){
            $.each($('.timepicker'),function(i,v){
                $(this).timepicker({showsTime: true});
            });
        });



        function myFunction(x) {
            require(["jquery"], function ($) {
                var depend = 'dependable'+x;

                var field  = document.getElementById(x).value;

                if(field !=1)
                {
                    $("#"+depend).css('display','none');
                    $("."+depend).css('display','none');
                }
                else{
                    $("#"+depend).css('display','');
                    $("."+depend).css('display','');
                }
            }); }
    </script>  