<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="membership-info">
    <div class="block-content">
        <div class="box box-information">
          <?php if(count($block->getSubscribedMembership()->getData())>0) {
              ?>
          	 <div class="table-wrapper membership-history">
        <table class="data table table-membership-history" id="my-membership-history">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Purchase Request') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col planname"><?php /* @escapeNotVerified */ echo __('Plan Name') ?></th>
                    <th scope="col" class="col price"><?php /* @escapeNotVerified */ echo __('Price') ?></th>
                    <th scope="col" class="col duration"><?php /* @escapeNotVerified */ echo __('Duration') ?></th>
                   <!--   <th scope="col" class="col category"><?php /* @escapeNotVerified */ //echo __('Category')?></th>-->
                    <th scope="col" class="col expiration"><?php /* @escapeNotVerified */ echo __('Expired On') ?></th>
                    <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($block->getSubscribedMembership() as $_membershipplan): ?>
                    <tr>
                        <td  class="col planname"><?php /* @escapeNotVerified */ echo $_membershipplan->getPlanName(); ?></td>
                        <td  class="col price"><?php /* @escapeNotVerified */ echo $_membershipplan->getPackagePrice() ?></td>
                       <!--   <td  class="col category"><?php /* @escapeNotVerified */ //echo $_request['category']?></td>-->
                        <td  class="col duration"><?php /* @escapeNotVerified */ echo $_membershipplan->getDuration();
                    echo __(' Day(s)')?></td>
                       
                         <td  class="col expiration"><?php /* @escapeNotVerified */ echo $this->formatDate(
                             $_membershipplan->getEndDate(),
                             \IntlDateFormatter::MEDIUM,
                             false
                         ) ?></td>
                          <td  class="col status"><?php /* @escapeNotVerified */ echo $_membershipplan->getStatus() ?></td>
                        
                        <?php //endforeach;?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $block->getPagerHtml(); ?>
    </div>
          <?php } else {
              ?>
          	  <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You Have Not Subscribed For Any Membership'); ?></span></div>
            <?php } ?>
        </div>
      
    </div>
</div>
<?php if(count($block->getSubscribedMembership()->getData())<=0) {
    ?>
<div class="ced-available-membership">
    <div class="ced-available-membership-block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Available Membership') ?></strong>
    </div>
    <div class="block-membership">
        <div class="box block-membership-data">
           <?php if(count($block->getMembershipPlan()->getData())>0) {
               foreach($block->getMembershipPlan() as $_membership) {
                   ?>
          <div class="block-membership-data-content">
				<div class="membership-package-info">
					<div class="membership-package-name"><?php echo $_membership->getPlanName()?></div>
					<div class="ced-membership-wrapper">
					<p class="membership-package-price">
						<label><?php echo __('Price')?></label>
						<span class="price"><?php echo $_membership->getPackagePrice()?></span>					</p>
					<p>
						<label><?php echo __('Duration')?></label>
						<strong><?php echo $_membership->getDuration();
                   echo __(' Day(s) from date of purchase')?></strong>
					</p>
					<div class="membership-package-description"><?php echo $_membership->getDescription()?></div>
					<div class="ced-membership-data-url">
					</div>
					 <div class="hidden-lg hidden-md hidden-sm hidden-xs col-xs-12">&nbsp;</div>
												<div class="action col-sm-6 col-xs-6 col-tn-12">
								<a href="<?php echo $this->getUrl('membership/membership/subscribe', ['product_id'=>$_membership->getProductId(),'price'=>$_membership->getPackagePrice()])?>"><?php echo __('Subscribe')?></a>
							</div>
							
							</div>
															
																			</div>
				</div>
				<?php }
               }?>
        </div>
       
    </div>
</div>
<?php } ?>