<?php
/**
 * Webkul Software
 *
 * @category  Webkul
 * @package   Webkul_Otp
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

?>
<div class="paypalOtpComponent" 
     data-mage-init='<?= /* @noEscape */ $block->getPaypalOtpJsInitParams(); ?>'>
    <div class="productPaypalOtp paypalOtpBtn"> 
        <span>Click here to verify otp</span>
    </div>
    <div
        data-mage-init='<?= /* @noEscape */ $block->getJsInitParams(); ?>'
        class="productPaypalDiv paypaldiv disablePaypalDiv">
    </div>
    <div class="otp-loader">
    </div>
</div>