<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Auction
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
?>

<?php
$viewModel = $block->getViewModel();
if (json_decode($viewModel->getConfigData('auction_entry_1/standard/standard_enable'), true)):?>
    <li class="nav item" id="link" >
        <a class="auctionlink" href="<?= /* @noEscape */ $block->getUrl('auction/index/index'); ?>"><?= /* @noEscape */ __('My Auctions') ?></a></li>
<?php endif; ?>
<script>
    require(
        [
            'jquery'
        ],
        function ($
        ) {
            $(document).ready(function () {

                 url = '<?= /* @noEscape */ $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true])?>';

                link = '<?= /* @noEscape */ $block->getUrl('auction/index/index')?>';

                if(url == link) {
                    $('#link').addClass("current");
                }

            });
        }
    );
</script>
