<?php
$modelHelper =  $block->helper('B2bmarkets\MultiStepReg\Helper\Data');
?>
<?php
$customHelper = $block->helper('B2bmarkets\Custom\Helper\Data');
$industries   = $customHelper->getIndustries();
?>
<form class="form create account form-create-account" action="<?= /* @noEscape */ $block->getUrl('multistepreg/index/save'); ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
    <input type="hidden" name="buyer_multi_step" value="1" />
    
    <fieldset class="fieldset personal">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Personal Information')) ?></span></legend><br>
        <?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
        <?php if ($_company->isEnabled()): ?>
            <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
        <?php endif ?>
        
        <div class="field required">
            <label class="label"><span><?= /* @noEscape */ __('Industry'); ?></span></label>
            <div class="control">
                <select class="required-entry input-select" name="buyer_industry">
                    
                    <option value=""> <?= /* @noEscape */ __('Select Industry'); ?></option>
                    <?php foreach ($industries as $industry_id => $industry_name) { ?>
                        <option value="<?= /* @noEscape */ $industry_id ?>"> <?= /* @noEscape */ $industry_name ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="field required">
            <label class="label"><span><?= /* @noEscape */ __('Company Type'); ?></span></label>
            <div class="control">
                <select class="required-entry input-select" name="buyer_company_type">
                    <?php $attribute = $modelHelper->getBuyerCompanyTypeAttribute();
$options = $attribute->getSource()->getAllOptions();?>
                    <option value=""> <?= /* @noEscape */ __('Select Company Type'); ?></option>
                    <?php foreach ($options as $instance) { ?>
                        <option value="<?= /* @noEscape */ $instance['value'] ?>"> <?= /* @noEscape */ $instance['label'] ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="actions-toolbar" style="padding: 0px;">
            <div class="primary">
                <button id="next_step" type="button" class="action submit primary" title="<?= /* @noEscape */ __('Next') ?>"><span><?= /* @noEscape */ __('Next') ?></span></button>
            </div>            
        </div>        
    </fieldset>
    <?php //if ($block->getShowAddressFields()) :?>
        <fieldset class="fieldset address" style="display: none;">
            <legend class="legend"><span><?= $escaper->escapeHtml(__('Business Information')) ?></span></legend><br>
            <input type="hidden" name="create_address" value="1" />            

            <div class="field required">
                <label for="buyer_company_website" class="label"><span><?= /* @noEscape */ __('Company Website'); ?></span></label>
                <div class="control">
                    <input type="text" name="buyer_company_website" value="" title="" class="input-text required-entry" id="buyer_company_website">
                </div>
            </div>
            <div class="field required">
                <label for="buyer_company_code" class="label"><span><?= /* @noEscape */ __('Company registration ID/Code'); ?></span></label>
                <div class="control">
                    <input type="text" name="buyer_company_code" value="" title="" class="input-text required-entry" id="buyer_company_code">
                </div>
            </div>
            <div class="field">
                <label for="buyer_registration_document_upload" class="label"><span><?= /* @noEscape */ __('Registration document Upload'); ?></span></label>
                <div class="control">
                    <input type="file"  name="buyer_registration_document_upload" class="input-text"/>
                    <!--<strong><note><?php //echo __('Note: Allowed file types are txt,excel,csv.');?></note></strong>-->
                </div>
            </div>
            <div class="field required">
                <label for="buyer_dun_bradstreet" class="label"><span><?= /* @noEscape */ __('Dun & Bradstreet'); ?></span></label>
                <div class="control">
                    <input type="text" name="buyer_dun_bradstreet" value="" title="" class="input-text required-entry" id="buyer_dun_bradstreet">
                </div>
            </div>
            <div class="field required">
                <label for="buyer_public_name" class="label"><span><?= /* @noEscape */ __('Public Name'); ?></span></label>
                <div class="control">
                    <input type="text" name="buyer_public_name" value="" title="" class="input-text required-entry" id="buyer_public_name">
                </div>
            </div>

            <?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
            <?php if ($_telephone->isEnabled()): ?>
                <?= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
            <?php endif ?>

            <?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
            <?php if ($_fax->isEnabled()): ?>
                <?= $_fax->setFax($block->getFormData()->getFax())->toHtml() ?>
            <?php endif ?>
            <?php //phpcs:disable?>
            <?php $_streetValidationClass = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street'); ?>
            <?php //phpcs:enable?>
            <div class="field street required">
                <label for="street_1" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span></label>
                <div class="control">
                    <input type="text" name="street[]" value="<?= $escaper->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>" id="street_1" class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>">
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php //phpcs:disable?>
                        <?php for ($_i = 2, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i <= $_n; $_i++) : ?>
                        <?php //phpcs:enable?>
                            <div class="field additional">
                                <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                    <span><?= $escaper->escapeHtml(__('Address')) ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="street[]" value="<?= $escaper->escapeHtmlAttr($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field required">
                <label for="city" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
                <div class="control">
                    <?php //phpcs:disable?>
                    <input type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="city">
                    <?php //phpcs:enable?>
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span></label>
                <div class="control">
                    <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select region_id" style="display:none;">
                        <option value=""><?= $escaper->escapeHtml(__('Please select a region, state or province.')) ?></option>
                    </select>
                    <?php //phpcs:disable?>
                    <input type="text" id="region" name="region" value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>" style="display:none;">
                    <?php //phpcs:enable?>
                </div>
            </div>

            <div class="field zip required">
                <label for="zip" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span></label>
                <div class="control">
                    <?php //phpcs:disable?>
                    <input type="text" name="postcode" value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
                    <?php //phpcs:enable?>
                </div>
            </div>

            <div class="field country required">
                <label for="country" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>
            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
            <?php endif;?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
            
            <div class="actions-toolbar" style="padding: 0px;">
                <div class="primary">
                    <button type="button" id="back_button" class="action primary" title="<?= /* @noEscape */ __('Back') ?>"><span><?= /* @noEscape */ __('Back') ?></span></button>
                    <button type="submit" class="action submit primary" title="<?= /* @noEscape */ __('Submit') ?>"><span><?= /* @noEscape */ __('Submit') ?></span></button>
                </div>                
            </div>

        </fieldset>
    <?php //endif;?> 
    <div class="clearfix"></div>   
</form>
<script>
require([
    'jquery',
    'mage/mage'
], function($){
    var dataForm = $('#form-validate');   
    dataForm.mage('validation', {});

    $(document).ready(function(){
        $(document).on('click','#next_step', function(){
            if ($('#form-validate').valid()) {
                $('.personal').hide();
                $('.address').show();
            }            
        });
        $(document).on('click','#back_button', function(){
            $('.personal').show();
            $('.address').hide();
        });
    });
});
</script>
<?php //if ($block->getShowAddressFields()) :?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                <?php //phpcs:disable?>
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                <?php //phpcs:enable?>
                "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
                <?php //phpcs:disable?>
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
                <?php //phpcs:enable?>
            }
        }
    }
</script>
<?php //endif;?>

